#cloud-config

## packages did not work, instead you can run all the cli commands in the runcmd.
# # Commands to run
runcmd:
  - "apt-get -y install make"
  - "apt-get -y install build-essential"
  - "apt-get -y install autoconf"
  - "apt-get -y install automake"
  - "apt-get -y install libpcre3-dev"
  - "apt-get -y install libevent-dev"
  - "apt-get -y install pkg-config"
  - "apt-get -y install zlib1g-dev"
  - "apt-get -y install libssl-dev"
  - "git clone https://github.com/RedisLabs/memtier_benchmark"
  - "cd memtier_benchmark"
  - "autoreconf -iv && ./configure && make install"
  - "${memtier_data_input_1}  -s ${test_acre_url_1} -p ${acre_port_1} -a ${access_key}"
  - "${memtier_benchmark_1}  -s ${test_acre_url_1} -p ${acre_port_1} -a ${access_key}"
  
  #- "rm -rf memtier_benchmark" # if we want to remove the folder